language: node_js
node_js:
- node
- iojs
- '6'
- '5'
- '4'
before_install:
# Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
- openssl aes-256-cbc -K $encrypted_d74b2ebf6c0f_key -iv $encrypted_d74b2ebf6c0f_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
# If the SDK is not already cached, download it and unpack it
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
# Here we use the decrypted service account credentials to authenticate the command line tool
- gcloud auth activate-service-account --key-file client-secret.json
script:
# Deploy the app
- gcloud -q preview app deploy app.yaml --promote
