language: node_js
node_js:
  - 6.9.1
before_script:
  - npm install -g iltorb
  - npm install -g gulp-cli
  - bower install
services: mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
matrix:
  fast_finish: true
