language: elixir
elixir:
  - 1.4.1
sudo: false
services:
  - postgresql
env:
  - MIX_ENV=test
before_script:
  - cp apps/udia/config/test.travis.exs apps/udia/config/test.exs
  - mix do ecto.create, ecto.migrate
