language: node_js
node_js:
  - "6.9.1"
services:
  - mongodb
before_install:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - npm install -g gulp-cli
install:
  - npm install
before_script:
  - gulp
after_script:
  - npm run coverage
