language: elixir
elixir:
  - 1.4.1
sudo: false
services:
  - postgresql: "9.4"
env:
  - MIX_ENV=test
before_script:
  - cp config/test.travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script:
  - mix coveralls.travis
after_script:
  - mix credo
