language: node_js
node_js:
  - 6.9.1
  - 7.2.0
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.12.0
before_script:
  - npm install -g gulp-cli
  - gem install sass
  - bower install
services: mongodb
