language: elixir
elixir:
  - 1.4.1
sudo: false
services:
  - postgresql
env:
  - MIX_ENV=test
before_script:
  - cp config/test.travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script:
  - mix coveralls.travis
  - mix credo
  - cd assets && npm run eslint
